In [ ]:
# 1.  Write  a  NumPy  program  to  create  an  element-wise  comparison  (greater,  greater_equal,  less  and less_equal)  of  two  given  arrays.
# 2.  Write  a  NumPy  program  to  create  an  array  of  all  the  even  integers  from  30  to  70.
# 3.  Write  a  NumPy  program  to  create  a  3x3  identity  matrix.
# 4.  Write  a  NumPy  program  to  create  a  vector  with  values  from  0  to  20  and  change  the  sign  of the  numbers  in  the  range  from  9  to  15.
# 5.  Write  a  NumPy  program  to  create  a  5x5  zero  matrix  with  elements  on  the  main  diagonal equal  to  1,  2,  3,  4,  5.
# 6.  Write  a  NumPy  program  to  compute  sum  of  all  elements,  sum  of  each  column  and  sum  of each  row  of  a  given  array.
# 7.  Write  a  NumPy  program  to  save  a  given  array  to  a  text  file  and  load  it.
# 8.  Write  a  NumPy  program  to  check  whether  two  arrays  are  equal  (element  wise)  or  not.
# 9.  Write  a  NumPy  program  to  create  a  4x4  array  with  random  values,  now  create  a  new  array from  the  said  array  swapping  first  and  last  rows.
# 10.  Write  a  NumPy  program  to  multiply  two  given  arrays  of  same  size  element-by-element

In [1]:
import numpy as np

In [2]:
# 1.element-wise  comparison  (greater,  greater_equal,  less  and less_equal)  of  two  given  arrays.
x=np.array([1,2,3])
y=np.array([1,5,6])
print("chech greater:")
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

# greater: Returns an array with the truth value of (x1 > x2) element-wise.
# greater_equal: Returns an array with the truth value of (x1 >= x2) element-wise.
# less: Returns an array with the truth value of (x1 < x2) element-wise.
# less_equal: Returns an array with the truth value of (x1 <= x2) element-wise.



chech greater:
[False False False]
[ True False False]
[False  True  True]
[ True  True  True]


In [7]:
x=[]
x=input("enter:").split()
print(x)

['qq', 'ww', 'f']


In [8]:
x=list(map(int,input().split()))
print(x)


[1, 2, 3]


In [9]:
# 2. create  an  array  of  all  the  even  integers  from  30  to  70.
x=np.arange(30,71,2)
print(x)


# arange() is a function in the NumPy library that returns an array with evenly spaced values within a given interval.
# numpy.arange([start, ]stop, [step, ]dtype=None)
# The function takes a start and stop value, along with an optional step size,
#  and returns an array with evenly spaced values between the start and stop values.

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
# 3. create  a  3x3  identity  matrix.
x=np.identity(4)
print(x)

# identity() is a function in the NumPy library that returns a square array with ones on the main diagonal and zeros elsewhere. 
# The function takes an integer argument n which specifies the number of rows (and columns) in the output array.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# 4.  Write  a  NumPy  program  to  create  a  vector  with  values  from  0  to  20  and  change  the  sign  of the  numbers  in  the  range  from  9  to  15.

x=np.arange(21)
x[9:16] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [25]:
# 5.  Write  a  NumPy  program  to  create  a  5x5  zero  matrix  with  elements  on  the  main  diagonal equal  to  1,  2,  3,  4,  5.
x=np.zeros((5,5))#for 2d
y=np.zeros(4)#for 1d
z=np.arange(0,9).reshape(3,3)
print(np.diag(np.diag(z)))
print(x)
print(y)


[[0 0 0]
 [0 4 0]
 [0 0 8]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0.]


In [22]:

x=np.diag([1,2,3])#a3x3 matrix with diagnol these and all others zeros.
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [33]:
# 6.  Write  a  NumPy  program  to  compute  sum  of  all  elements,  sum  of  each  column  and  sum  of each  row  of  a  given  array.
x=np.arange(10).reshape(5,2)
print("array=")
print(x)
print("sum=")
print(np.sum(x))
print("sum on row=")
print(np.sum(x,axis=0))
print("sum on col =",np.sum(x,axis=1))

array=
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
sum=
45
sum on row=
[20 25]
sum on col = [ 1  5  9 13 17]


In [36]:
# 7.  Write  a  NumPy  program  to  save  a  given  array  to  a  text  file  and  load  it.
x=np.arange(10).reshape(5,2)
np.savetxt('ary.txt',x)
y=np.loadtxt('ary.txt')
print(y)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [48]:
# 8.  Write  a  NumPy  program  to  check  whether  two  arrays  are  equal  (element  wise)  or  not.
x=np.array([1,2,3])
y=np.array([1,2,3])
print(np.array_equal(x, y))

True


In [55]:
# 9.  Write  a  NumPy  program  to  create  a  4x4  array  with  random  values,  now  create  a  new  array from  the  said  array  swapping  first  and  last  rows.
#swap!
x= np.arange(10).reshape(2,5)
print(x)
x[[0,1]]=x[[1,0]]#double bracket
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]


In [58]:
# 10.  Write  a  NumPy  program  to  multiply  two  given  arrays  of  same  size  element-by-element
x=np.arange(4)
print(x)
y=np.arange(4,8)
print(y)
z=x*y
print(z)


[0 1 2 3]
[4 5 6 7]
[ 0  5 12 21]
