In [ ]:
# Write  Python  program  to  create  two  matrices  (read  values  from  user)  and  find  the  following
# 1.  Dot  Product
# 2.  Transpose
# 3.  Trace
# 4.  Rank
# 5.  Determinant
# 6.  Inverse
# 7.  Eigenvalues  and  eigenvectors

In [2]:
import numpy as np


In [11]:
#WRONG!!!
r=int(input("Enter row="))
c=int(input("Enter col="))
m=list(map(int,input().split()))
x=np.array(m).reshape(r,c)

print(x)
n=list(map(int,input().split()))
print(n)

[[1 2]
 [3 4]]
[]


In [5]:
# 1.  Dot  Product
print("Dot product =")
print(np.dot(m,n))

Dot product =
32


In [8]:
x=[]
r=int(input("Enter row="))
c=int(input("Enter col="))
for i in range(r):
    for j in range(c):
        y=int(input("enter elemt:"))
        x.append(y)



In [9]:
print(x)

[1, 2, 3, 4]


In [12]:
#CORRECT!!!!!!!!!!
#creating 2d array from user in numpy
r=int(input("Enter row="))
c=int(input("Enter col="))
m=list(map(int,input().split()))
x=np.array(m).reshape(r,c)

r1=int(input("Enter row="))
c1=int(input("Enter col="))
m1=list(map(int,input().split()))
x1=np.array(m1).reshape(r1,c1)

In [13]:
print(x)
print(x1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [16]:
#dot 
#dot and multiply are diffrent
print(np.dot(x,x1))
print(x*x1)
print(np.multiply(x,x1))

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [24]:
# 2.  Transpose
print(np.transpose(x))
print(np.transpose(x1))


[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
[[1 3]
 [2 4]]


In [23]:
# 3.  Trace

print(x)
print(np.trace(x))
print(x1)
print(np.trace(x1))
#sum of its diagnols

[[1 2]
 [3 4]]
5
[[5 6]
 [7 8]]
13


In [31]:
# 4.  Rank
s=np.arange(10).reshape(2,5)
print(np.linalg.matrix_rank(s))
print(np.linalg.matrix_rank(x))
print(np.linalg.matrix_rank(x1))
#a rank(A) = min(m, n), where m is the number of rows and n is the number of columns.

2
2
2


In [27]:
# 5.  Determinant
print(np.linalg.det(x))
print(np.linalg.det(x1))

# The determinant of a matrix is a special number that can be calculated from a square matrix1. It is denoted as det(A), det A, or |A| where A is any square matrix2. The determinant of a matrix is the sum of products of the elements of any row or column and their corresponding co-factors34.

# For a 2x2 matrix, the determinant can be calculated as follows:

# If A = [a b; c d], then det(A) = ad - bc1.

# For a 3x3 matrix, the determinant can be calculated as follows:

# If A = [a b c; d e f; g h i], then det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)1

-2.0000000000000004
-2.000000000000005


In [28]:
# 6.  Inverse
print(np.linalg.inv(x))
print(np.linalg.inv(x1))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.   3. ]
 [ 3.5 -2.5]]


In [29]:
# 7.  Eigenvalues  and  eigenvectors
print(np.linalg.eig(x))
print(np.linalg.eig(x1))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
EigResult(eigenvalues=array([-0.15206735, 13.15206735]), eigenvectors=array([[-0.75868086, -0.59276441],
       [ 0.65146248, -0.80537591]]))
